### ISSUE TITLE
Vorto does not work with Related Links type

### ISSUE THREAD

**Issue by mfanuzzi** [umco/umbraco-vorto#77]
Hello,

I created a datatype called "Vorto Related Links", in which I set Vorto as the editor and chose "Related Links" as the datatype to wrap.  I then added a field with this new datatype to a document. I then went to enter content.  Though the editor displayed correctly, the values were not saving, and would be empty when I reload the page. Checking the UmbracoTraceLog reveals the following error upon "Save and Publish":

```
2016-12-13 16:21:57,937 [14] ERROR Our.Umbraco.Vorto.Web.PropertyEditors.VortoPropertyEditor+VortoPropertyValueEditor - [Thread 79] Error converting DB value to Editor
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: S. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.ReadInternal()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Our.Umbraco.Vorto.Web.PropertyEditors.VortoPropertyEditor.VortoPropertyValueEditor.ConvertEditorToDb(ContentPropertyData editorValue, Object currentValue)
2016-12-13 16:21:57,984 [14] INFO  Umbraco.Core.Publishing.PublishingStrategy - [Thread 79] Content 'Home Page' with Id '1059' has been published.
```

So it appears there is some issue with using this type. Has anyone else successfully extended Related Links with Vorto?

Thank you,
Michael

**Comment by defsteph** [comment]
Works for me. However, I've been having issues when changing data type, from non-vorto, to vorto wrapped property. My only solution so far has been to delete the content and re-create it.

**Comment by mattbrailsford** [comment]
Closing as have had no other confirmations since 2016. Please re-open if it's still a problem.
